services:
  web:
    build: ./
    ports:
      - "5006:5006"
    restart: always
    environment:
      - TZ=America/Santiago

  init-db:
    build: ./
    command: python app/scripts/init_mysql_db.py --fresh
    environment:
      - TZ=America/Santiago

  export-data-email:
    build: ./
    command: python app/scripts/export_mysql_db.py --mail backups@reyesandfriends.cl
    environment:
      - TZ=America/Santiago